AllCops:
  NewCops: enable

Metrics/BlockLength:
  Exclude:
    - 'config/**/*'

Layout/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 20

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/RescueStandardError:
  Enabled: false
