# inherit_from: .rubocop_todo.yml

Metrics/BlockLength:
  Exclude:
    - 'config/**/*'

# Configuration parameters: AllowHeredoc, AllowURI, URISchemes, IgnoreCopDirectives, IgnoredPatterns.
# URISchemes: http, https
Metrics/LineLength:
  Exclude:
    - 'config/**/*'
  Max: 120

Metrics/MethodLength:
  Max: 20

Style/BlockComments:
  Exclude:
    - 'spec/spec_helper.rb'

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/RescueStandardError:
  Enabled: false
